dist: trusty
sudo: false
language: scala
cache:
  directories:
  - $HOME/.ivy2
env:
  - NODE_VERSION=6
scala:
  - 2.11.6
jdk:
  - oraclejdk8
script:
  - nvm use $NODE_VERSION
  - sbt stage -DtsCompileMode=stage
